# Generated by Django 3.2.7 on 2021-12-17 09:14

import SETH.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETH', '0007_history_cert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='date',
            new_name='date_issued',
        ),
        migrations.AddField(
            model_name='certificate',
            name='date_expire',
            field=models.DateField(blank=True, default=SETH.models.Certificate.expire_date, null=True),
        ),
    ]
