# Generated by Django 3.2.7 on 2021-12-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SETH', '0008_auto_20211217_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='date_issued',
            new_name='date',
        ),
    ]
